In [8]:
import mysql.connector

In [9]:
# connect to sql database

mydb=mysql.connector.connect(
host="localhost",
user="root",
password="password",
database="toys_and_models")

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée)

In [3]:
mycursor=mydb.cursor()

In [ ]:
# create an empty table in the database for the city coordinates

mycursor.execute("CREATE TABLE countries( countryID INT PRIMARY KEY AUTO_INCREMENT, countryname VARCHAR(50) NOT NULL, countrycode VARCHAR(3) NOT NULL)")

In [4]:
# get all city/country names

mycursor.execute("SELECT country,city FROM customers")
myresult = mycursor.fetchall()

In [6]:
myresult

[('France', 'Nantes'),
 ('USA', 'Las Vegas'),
 ('Australia', 'Melbourne'),
 ('France', 'Nantes'),
 ('Norway', 'Stavern'),
 ('USA', 'San Rafael'),
 ('Poland', 'Warszawa'),
 ('Germany', 'Frankfurt'),
 ('USA', 'San Francisco'),
 ('USA', 'NYC'),
 ('Spain', 'Madrid'),
 ('Sweden', 'Luleå'),
 ('Denmark', 'Kobenhavn'),
 ('France', 'Lyon'),
 ('Singapore', 'Singapore'),
 ('USA', 'NYC'),
 ('USA', 'Allentown'),
 ('USA', 'Burlingame'),
 ('Singapore', 'Singapore'),
 ('Norway  ', 'Bergen'),
 ('USA', 'New Haven'),
 ('Portugal', 'Lisboa'),
 ('France', 'Lille'),
 ('France', 'Paris'),
 ('USA', 'Cambridge'),
 ('USA', 'Bridgewater'),
 ('Japan', 'Kita-ku'),
 ('USA', 'NYC'),
 ('Finland', 'Helsinki'),
 ('UK', 'Manchester'),
 ('Ireland', 'Dublin'),
 ('USA', 'Brickhaven'),
 ('UK', 'Liverpool'),
 ('Canada', 'Vancouver'),
 ('USA', 'Brickhaven'),
 ('USA', 'Pasadena'),
 ('Singapore', 'Singapore'),
 ('France', 'Strasbourg'),
 ('Hong Kong', 'Central Hong Kong'),
 ('Spain', 'Barcelona'),
 ('USA', 'Glendale'),
 ('Germany', 'Cunewalde'),
 ('Denmark', 'Århus'),
 ('Canada', 'Montréal'),
 ('Spain', 'Madrid'),
 ('USA', 'San Diego'),
 ('UK', 'Cowes'),
 ('France', 'Toulouse'),
 ('Germany', 'Frankfurt'),
 ('Italy', 'Torino'),
 ('France', 'Paris'),
 ('France', 'Versailles'),
 ('Germany', 'Köln'),
 ('Canada', 'Tsawassen'),
 ('Germany', 'München'),
 ('Australia', 'North Sydney'),
 ('Italy', 'Bergamo'),
 ('Australia', 'Chatswood'),
 ('USA', 'Cambridge'),
 ('Switzerland', 'Fribourg'),
 ('Switzerland', 'Genève'),
 ('Norway  ', 'Oslo'),
 ('Netherlands', 'Amsterdam'),
 ('Germany', 'Berlin'),
 ('Finland', 'Oulu'),
 ('Belgium', 'Bruxelles'),
 ('USA', 'White Plains'),
 ('USA', 'New Bedford'),
 ('USA', 'San Francisco'),
 ('New Zealand', 'Auckland  '),
 ('UK', 'London'),
 ('USA', 'Newark'),
 ('Australia', 'South Brisbane'),
 ('Finland', 'Espoo'),
 ('Germany', 'Brandenburg'),
 ('USA', 'Philadelphia'),
 ('Spain', 'Madrid'),
 ('USA', 'Los Angeles'),
 ('Ireland', 'Cork'),
 ('France', 'Marseille'),
 ('France', 'Reims'),
 ('South Africa', 'Hatfield'),
 ('New Zealand', 'Auckland'),
 ('Germany', 'Münster'),
 ('USA', 'Boston'),
 ('USA', 'Nashua'),
 ('Portugal', 'Lisboa'),
 ('Switzerland', 'Bern'),
 ('USA', 'Brickhaven'),
 ('Belgium', 'Charleroi'),
 ('Austria', 'Salzburg'),
 ('Philippines', 'Makati City'),
 ('Italy', 'Reggio Emilia'),
 ('Japan', 'Minato-ku'),
 ('France', 'Paris'),
 ('Germany', 'Stuttgart'),
 ('New Zealand', 'Wellington'),
 ('Germany', 'Munich'),
 ('USA', 'NYC'),
 ('Germany', 'Leipzig'),
 ('USA', 'Glendale'),
 ('Sweden', 'Bräcke'),
 ('USA', 'San Jose'),
 ('Austria', 'Graz'),
 ('USA', 'New Haven'),
 ('USA', 'NYC'),
 ('Spain', 'Madrid'),
 ('Germany', 'Aachen'),
 ('USA', 'New Bedford'),
 ('Spain', 'Madrid'),
 ('Australia', 'Glen Waverly'),
 ('Italy', 'Milan'),
 ('USA', 'Burbank'),
 ('Germany', 'Mannheim'),
 ('Russia', 'Saint Petersburg'),
 ('Israel', 'Herzlia'),
 ('Spain', 'Sevilla'),
 ('USA', 'Philadelphia'),
 ('USA', 'Brisbane'),
 ('UK', 'London'),
 ('USA', 'Boston'),
 ('New Zealand', 'Auckland  ')]

In [7]:
myresult.sort()

In [8]:
myresult

[('Australia', 'Chatswood'),
 ('Australia', 'Glen Waverly'),
 ('Australia', 'Melbourne'),
 ('Australia', 'North Sydney'),
 ('Australia', 'South Brisbane'),
 ('Austria', 'Graz'),
 ('Austria', 'Salzburg'),
 ('Belgium', 'Bruxelles'),
 ('Belgium', 'Charleroi'),
 ('Canada', 'Montréal'),
 ('Canada', 'Tsawassen'),
 ('Canada', 'Vancouver'),
 ('Denmark', 'Kobenhavn'),
 ('Denmark', 'Århus'),
 ('Finland', 'Espoo'),
 ('Finland', 'Helsinki'),
 ('Finland', 'Oulu'),
 ('France', 'Lille'),
 ('France', 'Lyon'),
 ('France', 'Marseille'),
 ('France', 'Nantes'),
 ('France', 'Nantes'),
 ('France', 'Paris'),
 ('France', 'Paris'),
 ('France', 'Paris'),
 ('France', 'Reims'),
 ('France', 'Strasbourg'),
 ('France', 'Toulouse'),
 ('France', 'Versailles'),
 ('Germany', 'Aachen'),
 ('Germany', 'Berlin'),
 ('Germany', 'Brandenburg'),
 ('Germany', 'Cunewalde'),
 ('Germany', 'Frankfurt'),
 ('Germany', 'Frankfurt'),
 ('Germany', 'Köln'),
 ('Germany', 'Leipzig'),
 ('Germany', 'Mannheim'),
 ('Germany', 'Munich'),
 ('Germany', 'München'),
 ('Germany', 'Münster'),
 ('Germany', 'Stuttgart'),
 ('Hong Kong', 'Central Hong Kong'),
 ('Ireland', 'Cork'),
 ('Ireland', 'Dublin'),
 ('Israel', 'Herzlia'),
 ('Italy', 'Bergamo'),
 ('Italy', 'Milan'),
 ('Italy', 'Reggio Emilia'),
 ('Italy', 'Torino'),
 ('Japan', 'Kita-ku'),
 ('Japan', 'Minato-ku'),
 ('Netherlands', 'Amsterdam'),
 ('New Zealand', 'Auckland'),
 ('New Zealand', 'Auckland  '),
 ('New Zealand', 'Auckland  '),
 ('New Zealand', 'Wellington'),
 ('Norway', 'Stavern'),
 ('Norway  ', 'Bergen'),
 ('Norway  ', 'Oslo'),
 ('Philippines', 'Makati City'),
 ('Poland', 'Warszawa'),
 ('Portugal', 'Lisboa'),
 ('Portugal', 'Lisboa'),
 ('Russia', 'Saint Petersburg'),
 ('Singapore', 'Singapore'),
 ('Singapore', 'Singapore'),
 ('Singapore', 'Singapore'),
 ('South Africa', 'Hatfield'),
 ('Spain', 'Barcelona'),
 ('Spain', 'Madrid'),
 ('Spain', 'Madrid'),
 ('Spain', 'Madrid'),
 ('Spain', 'Madrid'),
 ('Spain', 'Madrid'),
 ('Spain', 'Sevilla'),
 ('Sweden', 'Bräcke'),
 ('Sweden', 'Luleå'),
 ('Switzerland', 'Bern'),
 ('Switzerland', 'Fribourg'),
 ('Switzerland', 'Genève'),
 ('UK', 'Cowes'),
 ('UK', 'Liverpool'),
 ('UK', 'London'),
 ('UK', 'London'),
 ('UK', 'Manchester'),
 ('USA', 'Allentown'),
 ('USA', 'Boston'),
 ('USA', 'Boston'),
 ('USA', 'Brickhaven'),
 ('USA', 'Brickhaven'),
 ('USA', 'Brickhaven'),
 ('USA', 'Bridgewater'),
 ('USA', 'Brisbane'),
 ('USA', 'Burbank'),
 ('USA', 'Burlingame'),
 ('USA', 'Cambridge'),
 ('USA', 'Cambridge'),
 ('USA', 'Glendale'),
 ('USA', 'Glendale'),
 ('USA', 'Las Vegas'),
 ('USA', 'Los Angeles'),
 ('USA', 'NYC'),
 ('USA', 'NYC'),
 ('USA', 'NYC'),
 ('USA', 'NYC'),
 ('USA', 'NYC'),
 ('USA', 'Nashua'),
 ('USA', 'New Bedford'),
 ('USA', 'New Bedford'),
 ('USA', 'New Haven'),
 ('USA', 'New Haven'),
 ('USA', 'Newark'),
 ('USA', 'Pasadena'),
 ('USA', 'Philadelphia'),
 ('USA', 'Philadelphia'),
 ('USA', 'San Diego'),
 ('USA', 'San Francisco'),
 ('USA', 'San Francisco'),
 ('USA', 'San Jose'),
 ('USA', 'San Rafael'),
 ('USA', 'White Plains')]

In [9]:
# remove trailing whitespaces

for i in range(len(myresult)):
    myresult[i]=list(myresult[i])
    myresult[i][0]= myresult[i][0].strip()
    myresult[i][1]= myresult[i][1].strip()

In [10]:
myresult

[['Australia', 'Chatswood'],
 ['Australia', 'Glen Waverly'],
 ['Australia', 'Melbourne'],
 ['Australia', 'North Sydney'],
 ['Australia', 'South Brisbane'],
 ['Austria', 'Graz'],
 ['Austria', 'Salzburg'],
 ['Belgium', 'Bruxelles'],
 ['Belgium', 'Charleroi'],
 ['Canada', 'Montréal'],
 ['Canada', 'Tsawassen'],
 ['Canada', 'Vancouver'],
 ['Denmark', 'Kobenhavn'],
 ['Denmark', 'Århus'],
 ['Finland', 'Espoo'],
 ['Finland', 'Helsinki'],
 ['Finland', 'Oulu'],
 ['France', 'Lille'],
 ['France', 'Lyon'],
 ['France', 'Marseille'],
 ['France', 'Nantes'],
 ['France', 'Nantes'],
 ['France', 'Paris'],
 ['France', 'Paris'],
 ['France', 'Paris'],
 ['France', 'Reims'],
 ['France', 'Strasbourg'],
 ['France', 'Toulouse'],
 ['France', 'Versailles'],
 ['Germany', 'Aachen'],
 ['Germany', 'Berlin'],
 ['Germany', 'Brandenburg'],
 ['Germany', 'Cunewalde'],
 ['Germany', 'Frankfurt'],
 ['Germany', 'Frankfurt'],
 ['Germany', 'Köln'],
 ['Germany', 'Leipzig'],
 ['Germany', 'Mannheim'],
 ['Germany', 'Munich'],
 ['Germany', 'München'],
 ['Germany', 'Münster'],
 ['Germany', 'Stuttgart'],
 ['Hong Kong', 'Central Hong Kong'],
 ['Ireland', 'Cork'],
 ['Ireland', 'Dublin'],
 ['Israel', 'Herzlia'],
 ['Italy', 'Bergamo'],
 ['Italy', 'Milan'],
 ['Italy', 'Reggio Emilia'],
 ['Italy', 'Torino'],
 ['Japan', 'Kita-ku'],
 ['Japan', 'Minato-ku'],
 ['Netherlands', 'Amsterdam'],
 ['New Zealand', 'Auckland'],
 ['New Zealand', 'Auckland'],
 ['New Zealand', 'Auckland'],
 ['New Zealand', 'Wellington'],
 ['Norway', 'Stavern'],
 ['Norway', 'Bergen'],
 ['Norway', 'Oslo'],
 ['Philippines', 'Makati City'],
 ['Poland', 'Warszawa'],
 ['Portugal', 'Lisboa'],
 ['Portugal', 'Lisboa'],
 ['Russia', 'Saint Petersburg'],
 ['Singapore', 'Singapore'],
 ['Singapore', 'Singapore'],
 ['Singapore', 'Singapore'],
 ['South Africa', 'Hatfield'],
 ['Spain', 'Barcelona'],
 ['Spain', 'Madrid'],
 ['Spain', 'Madrid'],
 ['Spain', 'Madrid'],
 ['Spain', 'Madrid'],
 ['Spain', 'Madrid'],
 ['Spain', 'Sevilla'],
 ['Sweden', 'Bräcke'],
 ['Sweden', 'Luleå'],
 ['Switzerland', 'Bern'],
 ['Switzerland', 'Fribourg'],
 ['Switzerland', 'Genève'],
 ['UK', 'Cowes'],
 ['UK', 'Liverpool'],
 ['UK', 'London'],
 ['UK', 'London'],
 ['UK', 'Manchester'],
 ['USA', 'Allentown'],
 ['USA', 'Boston'],
 ['USA', 'Boston'],
 ['USA', 'Brickhaven'],
 ['USA', 'Brickhaven'],
 ['USA', 'Brickhaven'],
 ['USA', 'Bridgewater'],
 ['USA', 'Brisbane'],
 ['USA', 'Burbank'],
 ['USA', 'Burlingame'],
 ['USA', 'Cambridge'],
 ['USA', 'Cambridge'],
 ['USA', 'Glendale'],
 ['USA', 'Glendale'],
 ['USA', 'Las Vegas'],
 ['USA', 'Los Angeles'],
 ['USA', 'NYC'],
 ['USA', 'NYC'],
 ['USA', 'NYC'],
 ['USA', 'NYC'],
 ['USA', 'NYC'],
 ['USA', 'Nashua'],
 ['USA', 'New Bedford'],
 ['USA', 'New Bedford'],
 ['USA', 'New Haven'],
 ['USA', 'New Haven'],
 ['USA', 'Newark'],
 ['USA', 'Pasadena'],
 ['USA', 'Philadelphia'],
 ['USA', 'Philadelphia'],
 ['USA', 'San Diego'],
 ['USA', 'San Francisco'],
 ['USA', 'San Francisco'],
 ['USA', 'San Jose'],
 ['USA', 'San Rafael'],
 ['USA', 'White Plains']]

In [12]:
# keep unqiue values

for i in range(len(myresult)):
    myresult[i]=tuple(myresult[i])
myresult2=set(myresult)

In [15]:
myresult2

{('Australia', 'Chatswood'),
 ('Australia', 'Glen Waverly'),
 ('Australia', 'Melbourne'),
 ('Australia', 'North Sydney'),
 ('Australia', 'South Brisbane'),
 ('Austria', 'Graz'),
 ('Austria', 'Salzburg'),
 ('Belgium', 'Bruxelles'),
 ('Belgium', 'Charleroi'),
 ('Canada', 'Montréal'),
 ('Canada', 'Tsawassen'),
 ('Canada', 'Vancouver'),
 ('Denmark', 'Kobenhavn'),
 ('Denmark', 'Århus'),
 ('Finland', 'Espoo'),
 ('Finland', 'Helsinki'),
 ('Finland', 'Oulu'),
 ('France', 'Lille'),
 ('France', 'Lyon'),
 ('France', 'Marseille'),
 ('France', 'Nantes'),
 ('France', 'Paris'),
 ('France', 'Reims'),
 ('France', 'Strasbourg'),
 ('France', 'Toulouse'),
 ('France', 'Versailles'),
 ('Germany', 'Aachen'),
 ('Germany', 'Berlin'),
 ('Germany', 'Brandenburg'),
 ('Germany', 'Cunewalde'),
 ('Germany', 'Frankfurt'),
 ('Germany', 'Köln'),
 ('Germany', 'Leipzig'),
 ('Germany', 'Mannheim'),
 ('Germany', 'Munich'),
 ('Germany', 'München'),
 ('Germany', 'Münster'),
 ('Germany', 'Stuttgart'),
 ('Hong Kong', 'Central Hong Kong'),
 ('Ireland', 'Cork'),
 ('Ireland', 'Dublin'),
 ('Israel', 'Herzlia'),
 ('Italy', 'Bergamo'),
 ('Italy', 'Milan'),
 ('Italy', 'Reggio Emilia'),
 ('Italy', 'Torino'),
 ('Japan', 'Kita-ku'),
 ('Japan', 'Minato-ku'),
 ('Netherlands', 'Amsterdam'),
 ('New Zealand', 'Auckland'),
 ('New Zealand', 'Wellington'),
 ('Norway', 'Bergen'),
 ('Norway', 'Oslo'),
 ('Norway', 'Stavern'),
 ('Philippines', 'Makati City'),
 ('Poland', 'Warszawa'),
 ('Portugal', 'Lisboa'),
 ('Russia', 'Saint Petersburg'),
 ('Singapore', 'Singapore'),
 ('South Africa', 'Hatfield'),
 ('Spain', 'Barcelona'),
 ('Spain', 'Madrid'),
 ('Spain', 'Sevilla'),
 ('Sweden', 'Bräcke'),
 ('Sweden', 'Luleå'),
 ('Switzerland', 'Bern'),
 ('Switzerland', 'Fribourg'),
 ('Switzerland', 'Genève'),
 ('UK', 'Cowes'),
 ('UK', 'Liverpool'),
 ('UK', 'London'),
 ('UK', 'Manchester'),
 ('USA', 'Allentown'),
 ('USA', 'Boston'),
 ('USA', 'Brickhaven'),
 ('USA', 'Bridgewater'),
 ('USA', 'Brisbane'),
 ('USA', 'Burbank'),
 ('USA', 'Burlingame'),
 ('USA', 'Cambridge'),
 ('USA', 'Glendale'),
 ('USA', 'Las Vegas'),
 ('USA', 'Los Angeles'),
 ('USA', 'NYC'),
 ('USA', 'Nashua'),
 ('USA', 'New Bedford'),
 ('USA', 'New Haven'),
 ('USA', 'Newark'),
 ('USA', 'Pasadena'),
 ('USA', 'Philadelphia'),
 ('USA', 'San Diego'),
 ('USA', 'San Francisco'),
 ('USA', 'San Jose'),
 ('USA', 'San Rafael'),
 ('USA', 'White Plains')}

In [16]:
myresult3=list(myresult2)

In [17]:
myresult3.sort()

In [18]:
myresult3

[('Australia', 'Chatswood'),
 ('Australia', 'Glen Waverly'),
 ('Australia', 'Melbourne'),
 ('Australia', 'North Sydney'),
 ('Australia', 'South Brisbane'),
 ('Austria', 'Graz'),
 ('Austria', 'Salzburg'),
 ('Belgium', 'Bruxelles'),
 ('Belgium', 'Charleroi'),
 ('Canada', 'Montréal'),
 ('Canada', 'Tsawassen'),
 ('Canada', 'Vancouver'),
 ('Denmark', 'Kobenhavn'),
 ('Denmark', 'Århus'),
 ('Finland', 'Espoo'),
 ('Finland', 'Helsinki'),
 ('Finland', 'Oulu'),
 ('France', 'Lille'),
 ('France', 'Lyon'),
 ('France', 'Marseille'),
 ('France', 'Nantes'),
 ('France', 'Paris'),
 ('France', 'Reims'),
 ('France', 'Strasbourg'),
 ('France', 'Toulouse'),
 ('France', 'Versailles'),
 ('Germany', 'Aachen'),
 ('Germany', 'Berlin'),
 ('Germany', 'Brandenburg'),
 ('Germany', 'Cunewalde'),
 ('Germany', 'Frankfurt'),
 ('Germany', 'Köln'),
 ('Germany', 'Leipzig'),
 ('Germany', 'Mannheim'),
 ('Germany', 'Munich'),
 ('Germany', 'München'),
 ('Germany', 'Münster'),
 ('Germany', 'Stuttgart'),
 ('Hong Kong', 'Central Hong Kong'),
 ('Ireland', 'Cork'),
 ('Ireland', 'Dublin'),
 ('Israel', 'Herzlia'),
 ('Italy', 'Bergamo'),
 ('Italy', 'Milan'),
 ('Italy', 'Reggio Emilia'),
 ('Italy', 'Torino'),
 ('Japan', 'Kita-ku'),
 ('Japan', 'Minato-ku'),
 ('Netherlands', 'Amsterdam'),
 ('New Zealand', 'Auckland'),
 ('New Zealand', 'Wellington'),
 ('Norway', 'Bergen'),
 ('Norway', 'Oslo'),
 ('Norway', 'Stavern'),
 ('Philippines', 'Makati City'),
 ('Poland', 'Warszawa'),
 ('Portugal', 'Lisboa'),
 ('Russia', 'Saint Petersburg'),
 ('Singapore', 'Singapore'),
 ('South Africa', 'Hatfield'),
 ('Spain', 'Barcelona'),
 ('Spain', 'Madrid'),
 ('Spain', 'Sevilla'),
 ('Sweden', 'Bräcke'),
 ('Sweden', 'Luleå'),
 ('Switzerland', 'Bern'),
 ('Switzerland', 'Fribourg'),
 ('Switzerland', 'Genève'),
 ('UK', 'Cowes'),
 ('UK', 'Liverpool'),
 ('UK', 'London'),
 ('UK', 'Manchester'),
 ('USA', 'Allentown'),
 ('USA', 'Boston'),
 ('USA', 'Brickhaven'),
 ('USA', 'Bridgewater'),
 ('USA', 'Brisbane'),
 ('USA', 'Burbank'),
 ('USA', 'Burlingame'),
 ('USA', 'Cambridge'),
 ('USA', 'Glendale'),
 ('USA', 'Las Vegas'),
 ('USA', 'Los Angeles'),
 ('USA', 'NYC'),
 ('USA', 'Nashua'),
 ('USA', 'New Bedford'),
 ('USA', 'New Haven'),
 ('USA', 'Newark'),
 ('USA', 'Pasadena'),
 ('USA', 'Philadelphia'),
 ('USA', 'San Diego'),
 ('USA', 'San Francisco'),
 ('USA', 'San Jose'),
 ('USA', 'San Rafael'),
 ('USA', 'White Plains')]

In [12]:
from  geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="Baptiste")

In [13]:
city ="Salon-de-Provence"
country ="France"
loc = geolocator.geocode(city+','+ country)
print("latitude is :-" ,loc.latitude,"\nlongtitude is:-" ,loc.longitude)

latitude is :- 43.6405237
longtitude is:- 5.0980225

In [24]:
for i in range(len(myresult3)):
    myresult3[i]=list(myresult3[i])

In [34]:
# Fix a spelling mistake

myresult3[10][1]='Tsawwassen'

In [38]:
# add coordinates for every city

for i in myresult3:
    loc = geolocator.geocode(i[1]+','+ i[0])
    i+=[loc.latitude]
    i+=[loc.longitude]

In [39]:
myresult3

[['Australia', 'Chatswood', -33.7944797, 151.1818571],
 ['Australia', 'Glen Waverly', -37.9034919, 145.1645264945447],
 ['Australia', 'Melbourne', -37.8142176, 144.9631608],
 ['Australia', 'North Sydney', -33.8354519, 151.2083011],
 ['Australia', 'South Brisbane', -27.482134, 153.0223507],
 ['Austria', 'Graz', 47.0708678, 15.4382786],
 ['Austria', 'Salzburg', 47.7981346, 13.0464806],
 ['Belgium', 'Bruxelles', 50.8465573, 4.351697],
 ['Belgium', 'Charleroi', 50.4120332, 4.4436244],
 ['Canada', 'Montréal', 45.4972159, -73.6103642],
 ['Canada', 'Tsawwassen', 49.02428425, -123.07622361968933],
 ['Canada', 'Vancouver', 49.2608724, -123.1139529],
 ['Denmark', 'Kobenhavn', 55.6867243, 12.5700724],
 ['Denmark', 'Århus', 56.1496278, 10.2134046],
 ['Finland', 'Espoo', 60.2241869, 24.6603626],
 ['Finland', 'Helsinki', 60.1674098, 24.9425769],
 ['Finland', 'Oulu', 65.0118734, 25.4716809],
 ['France', 'Lille', 50.6365654, 3.0635282],
 ['France', 'Lyon', 45.7578137, 4.8320114],
 ['France', 'Marseille', 43.2961743, 5.3699525],
 ['France', 'Nantes', 47.2186371, -1.5541362],
 ['France', 'Paris', 48.8566969, 2.3514616],
 ['France', 'Reims', 49.2577886, 4.031926],
 ['France', 'Strasbourg', 48.584614, 7.7507127],
 ['France', 'Toulouse', 43.6044622, 1.4442469],
 ['France', 'Versailles', 48.8035403, 2.1266886],
 ['Germany', 'Aachen', 50.776351, 6.083862],
 ['Germany', 'Berlin', 52.5170365, 13.3888599],
 ['Germany', 'Brandenburg', 52.8455492, 13.2461296],
 ['Germany', 'Cunewalde', 51.098481, 14.514475],
 ['Germany', 'Frankfurt', 50.1106444, 8.6820917],
 ['Germany', 'Köln', 50.938361, 6.959974],
 ['Germany', 'Leipzig', 51.3406321, 12.3747329],
 ['Germany', 'Mannheim', 49.489591, 8.467236],
 ['Germany', 'Munich', 48.1371079, 11.5753822],
 ['Germany', 'München', 48.1371079, 11.5753822],
 ['Germany', 'Münster', 51.9625101, 7.6251879],
 ['Germany', 'Stuttgart', 48.7784485, 9.1800132],
 ['Hong Kong', 'Central Hong Kong', 22.2850394, 114.1583819],
 ['Ireland', 'Cork', 51.8979282, -8.4705806],
 ['Ireland', 'Dublin', 53.3497645, -6.2602732],
 ['Israel', 'Herzlia', 32.1656255, 34.8469023],
 ['Italy', 'Bergamo', 45.756655699999996, 9.754219200862249],
 ['Italy', 'Milan', 45.4668, 9.1905],
 ['Italy', 'Reggio Emilia', 44.608664, 10.594796841892734],
 ['Italy', 'Torino', 45.0677551, 7.6824892],
 ['Japan', 'Kita-ku', 35.755838, 139.736687],
 ['Japan', 'Minato-ku', 35.6432274, 139.7400553],
 ['Netherlands', 'Amsterdam', 52.3727598, 4.8936041],
 ['New Zealand', 'Auckland', -36.852095, 174.7631803],
 ['New Zealand', 'Wellington', -41.2887953, 174.7772114],
 ['Norway', 'Bergen', 60.3943055, 5.3259192],
 ['Norway', 'Oslo', 59.9133301, 10.7389701],
 ['Norway', 'Stavern', 58.9983397, 10.0360061],
 ['Philippines', 'Makati City', 14.5568853, 121.023532],
 ['Poland', 'Warszawa', 52.2319581, 21.0067249],
 ['Portugal', 'Lisboa', 38.7077507, -9.1365919],
 ['Russia', 'Saint Petersburg', 59.938732, 30.316229],
 ['Singapore', 'Singapore', 1.3408630000000001, 103.83039182212079],
 ['South Africa', 'Hatfield', -25.7508333, 28.2430556],
 ['Spain', 'Barcelona', 41.3828939, 2.1774322],
 ['Spain', 'Madrid', 40.4167047, -3.7035825],
 ['Spain', 'Sevilla', 37.3886303, -5.9953403],
 ['Sweden', 'Bräcke', 62.83507915, 15.640969658085652],
 ['Sweden', 'Luleå', 65.5831187, 22.1459535],
 ['Switzerland', 'Bern', 46.9482713, 7.4514512],
 ['Switzerland', 'Fribourg', 46.6789116, 7.1027113],
 ['Switzerland', 'Genève', 46.2017559, 6.1466014],
 ['UK', 'Cowes', 50.757624750000005, -1.3035640666867363],
 ['UK', 'Liverpool', 53.407154, -2.991665],
 ['UK', 'London', 51.5073219, -0.1276474],
 ['UK', 'Manchester', 53.4794892, -2.2451148],
 ['USA', 'Allentown', 40.6022059, -75.4712794],
 ['USA', 'Boston', 42.3602534, -71.0582912],
 ['USA', 'Brickhaven', 35.5748754, -79.0289059],
 ['USA', 'Bridgewater', 41.9903787, -70.9750426],
 ['USA', 'Brisbane', 37.687165, -122.4027942],
 ['USA', 'Burbank', 34.1816482, -118.3258554],
 ['USA', 'Burlingame', 37.5841026, -122.3660825],
 ['USA', 'Cambridge', 42.3750997, -71.1056157],
 ['USA', 'Glendale', 34.1469416, -118.2478471],
 ['USA', 'Las Vegas', 36.1672559, -115.1485163],
 ['USA', 'Los Angeles', 34.0536909, -118.2427666],
 ['USA', 'NYC', 40.7127281, -74.0060152],
 ['USA', 'Nashua', 42.7653662, -71.467566],
 ['USA', 'New Bedford', 41.6362152, -70.934205],
 ['USA', 'New Haven', 41.3082138, -72.9250518],
 ['USA', 'Newark', 40.735657, -74.1723667],
 ['USA', 'Pasadena', 34.1476452, -118.1444779],
 ['USA', 'Philadelphia', 39.9527237, -75.1635262],
 ['USA', 'San Diego', 32.7174209, -117.1627714],
 ['USA', 'San Francisco', 37.7790262, -122.4199061],
 ['USA', 'San Jose', 37.3361905, -121.8905833],
 ['USA', 'San Rafael', 37.9735346, -122.5310874],
 ['USA', 'White Plains', 41.0339862, -73.7629097]]

In [43]:
mycursor.executemany("INSERT INTO cities (countryname,cityname,latitude,longitude) VALUES (%s, %s, %s, %s)",myresult3)

In [44]:
mydb.commit()